import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{getFirestore,collection,addDoc,getDocs,query,orderBy,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";import{getStorage,ref,uploadBytes,getDownloadURL}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
const config={apiKey:"PASTE_YOUR_FIREBASE_API_KEY",authDomain:"PASTE_YOUR_PROJECT.firebaseapp.com",projectId:"PASTE_YOUR_PROJECT_ID",storageBucket:"PASTE_YOUR_PROJECT.appspot.com",messagingSenderId:"PASTE_YOUR_SENDER_ID",appId:"PASTE_YOUR_APP_ID"};const ready=!Object.values(config).some(x=>x.includes("PASTE_YOUR"));let auth,db,storage,provider,user;
if(ready){const app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);provider=new GoogleAuthProvider();onAuthStateChanged(auth,u=>{user=u;update()});loadReviews()}else update();
function update(){["reviewForm","supportForm"].forEach(id=>document.getElementById(id).classList.toggle("hidden",!user));document.getElementById("reviewLogin").innerHTML=user?`<p>Ingelogd als <b>${esc(user.displayName||user.email)}</b></p>`:`<button class="btn" onclick="login()">Sign in with Google</button>`;document.getElementById("supportLogin").innerHTML=user?`<p>Ingelogd als <b>${esc(user.displayName||user.email)}</b></p>`:`<button class="btn" onclick="login()">Sign in with Google</button>`}
window.login=async()=>{if(!ready)return msg("Firebase is nog niet ingesteld. Volg README_SETUP.txt.");try{await signInWithPopup(auth,provider)}catch(e){console.error(e);msg("Google-login mislukt.")}};
window.openModal=id=>document.getElementById(id).classList.add("show");window.closeModal=id=>document.getElementById(id).classList.remove("show");window.msg=s=>{let t=document.getElementById("toast");t.textContent=s;t.style.display="block";setTimeout(()=>t.style.display="none",3000)};window.addEventListener("click",e=>{if(e.target.classList.contains("modal"))e.target.classList.remove("show")});
document.getElementById("reviewForm").onsubmit=async e=>{e.preventDefault();if(!user)return login();try{await addDoc(collection(db,"reviews"),{uid:user.uid,name:document.getElementById("rname").value.trim(),rating:+document.getElementById("rating").value,text:document.getElementById("rtext").value.trim(),createdAt:serverTimestamp()});e.target.reset();closeModal("reviewModal");msg("Review geplaatst.");loadReviews()}catch(x){console.error(x);msg("Review kon niet worden geplaatst.")}};
async function loadReviews(){if(!ready)return;try{let s=await getDocs(query(collection(db,"reviews"),orderBy("createdAt","desc"))),el=document.getElementById("reviewsList");if(s.empty){el.innerHTML='<div class="empty">Nog geen reviews geplaatst.</div>';return}el.innerHTML="";s.forEach(d=>{let r=d.data();el.innerHTML+=`<article class="review"><b>${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</b><p>“${esc(r.text)}”</p><strong>— ${esc(r.name)}</strong></article>`})}catch(e){console.error(e)}}
document.getElementById("supportForm").onsubmit=async e=>{e.preventDefault();if(!user)return login();let f=document.getElementById("proof").files[0];if(!f||f.size>5242880)return msg("Aankoopbewijs ontbreekt of is groter dan 5 MB.");try{let n=f.name.replace(/[^a-zA-Z0-9._-]/g,"_"),r=ref(storage,`support/${user.uid}/${Date.now()}_${n}`);await uploadBytes(r,f);let url=await getDownloadURL(r);await addDoc(collection(db,"supportTickets"),{uid:user.uid,email:user.email||"",name:document.getElementById("sname").value.trim(),purchase:document.getElementById("purchase").value.trim(),problem:document.getElementById("problem").value.trim(),proofUrl:url,status:"open",createdAt:serverTimestamp()});e.target.reset();closeModal("supportModal");msg("Supportmelding verstuurd.")}catch(x){console.error(x);msg("Supportmelding kon niet worden verstuurd.")}};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}